name: CI
on:
  push:
    branches:
      - master
jobs:
  testdns:
    name: test coredns
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install coredns
        run: |
          wget https://github.com/coredns/coredns/releases/download/v1.8.6/coredns_1.8.6_linux_amd64.tgz
          tar xzf coredns_1.8.6_linux_amd64.tgz
      - name: Get resolv.conf
        run: |
          cat /etc/resolv.conf
          id
          sudo ls
      - name: Start coredns
        run: |
          sudo ./coredns -conf conf/coredns.conf &
          sudo systemctl stop systemd-resolved
          echo "nameserver 127.0.0.54" | sudo tee /etc/resolv.conf
      - name: Test resolver
        run: |
          dig -t soa example.org
